services:
  kong:
    container_name: kong
    ports:
      - "80:80"
    image: kong/kong-gateway:3.12.0.1
    volumes:  
      - ./kong.yml:/kong/declarative/kong.yml
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml
      - KONG_PROXY_LISTEN=0.0.0.0:80
